import Head from 'next/head'

import Navbar from '../Components/Navbar/navbar'
import Favorites from '../Components/[favorites]/[favorites]'

import Mainsection from '../Components/mainsection/mainsection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Villa</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <Mainsection />
      </main>
      <div className="forwave">
        <svg xmlns="http://www.w3.org/2000/svg" className="wave1" viewBox="0 0 1440 320"><path fill="#cd9b1d" fill-opacity="0.5" d="M0,128L48,133.3C96,139,192,149,288,170.7C384,192,480,224,576,234.7C672,245,768,235,864,234.7C960,235,1056,245,1152,229.3C1248,213,1344,171,1392,149.3L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
        <svg xmlns="http://www.w3.org/2000/svg" className="wave2" viewBox="0 0 1440 320"><path fill="#cd9b1d" fill-opacity="0.5" d="M0,96L120,80C240,64,480,32,720,48C960,64,1200,128,1320,160L1440,192L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z"></path></svg>
      </div>
      <section>
        <Favorites />
      </section>
    </>
  )
}